### ISSUE TITLE
unsupport read uri from content provider(not file uri)

### ISSUE THREAD

**Issue by zsqw123** [xihan123/SignHook#108]
unsupport read uri from content provider(not file uri), log here:

![](https://github.com/xihan123/SignHook/assets/49520432/8b2c0048-fdf9-490f-9dde-7293e0541502)

I'll create a PR for this issue

**Comment by zsqw123** [comment]
direct use uri's path as file path will meets a lot of issues for high version of Android, we should adapt that by copy it to temporary dir

![image](https://github.com/xihan123/SignHook/assets/49520432/523eb807-47d1-45b7-a98d-4f26ae120db9)

**Comment by zsqw123** [comment]
I can see some feedbacks in coolapk, after this MR, this bug will be fixed

![254d0269896c206eabb43ca7ccd38e82_720](https://github.com/xihan123/SignHook/assets/49520432/36186c85-1ce8-4a20-93cd-5def899f8012)

**Comment by xihan123** [comment]
其实没有必要支持这个啊，复制到临时目录还要IO读写，大应用浪费时间。固定放到一个目录，每次都从这个目录选就完事了

**Comment by zsqw123** [comment]
首先是我遇到了签名读取错误的问题，然后我就搜了很久没找到答案，最后在一篇酷安文章偶然翻到是因为不是一层层点进去的才发现原来是没适配 content provider，我相信很多人也遇到了相关问题；但最后我选择去看代码，真正 debug 去看错误堆栈然后来反馈的问题，我相信更有参考价值。

其次是由于 Android 权限机制，事实上高版本默认已经不允许使用读取文件路径来访问文件了，ContentProvider 是目前的推荐方式，这种方式必须 copy 文件到自己目录去操作，这个耗时是符合预期的，反倒是去获取整个内置储存，然后拿目录读取这种方式才是不应该的；其次由于是顺序读写，大多数设备其实拷贝都不太需要很长的时间。（真的觉得很耗费时间的话，进度条也是很好做的）

**Comment by xihan123** [comment]
有没有一种可能，现在用的就是ContentProvider了，只不过只支持根目录下选取的文件，因为我代码里面限定了。

**Comment by zsqw123** [comment]
好吧，听你的，你是作者
