### ISSUE TITLE
如何配置在lspatch的便携模式下

### ISSUE THREAD

**Issue by xyjs666** [xihan123/SignHook#113]
便携模式下 无法打开签名助手 也没有配置界面 对应用目标(某点)进行勾选以及更改签名 请教如何解决

**Comment by xihan123** [comment]
很明显你理解错了。你需要的是将签名助手打包进目标应用，然后目标应用有存储权限读取外部存储下已配置好的假签名值

**Comment by xyjs666** [comment]
明白 按照你的说法 确实可以解决我的问题 现在还有2点疑虑
1.我使用lspatch将签名助手打包到某点 没有进行常规的勾选软件操作 那么它如何生效的 为打包进去就可以直接针对某点生效了
2.外部存储配置的假签名值 如何配置 配置规则以及路径在哪
望解答 感谢!

**Comment by xihan123** [comment]
所以你还是没有理解，能仔细看说明吗
1.是打包进QQ/微信，其原理是在QQ/微信获取某点的签名值时获取到的是假的签名值
某点调用了QQ，QQ里面有相关处理这种调用的验证，验证的就是获取到的签名值，具体如何欺骗看源码
调用者=某点
被调用者=QQ
2.如何获取签名值看使用说明，把要替换的真的签名值填到伪造签名那里就行了，配置文件路径在/sdcard/Download/SignHelper/option.json

**Comment by xyjs666** [comment]
收到 我之前理解反了 感谢!

**Comment by yongxiangzheng** [comment]
那如果拼多多（官方版本）想调用微信（lspach注入模块的版本）登录，是不是只要把微信的签名改成官方的签名，就能正常调用登录了？

**Comment by xihan123** [comment]
> 那如果拼多多（官方版本）想调用微信（lspach注入模块的版本）登录，是不是只要把微信的签名改成官方的签名，就能正常调用登录了？

理论上是这样
