### ISSUE TITLE
从"最近"中选择APK获取签名读取失败

### ISSUE THREAD

**Issue by aoguai** [xihan123/SignHook#121]
从"最近"中选择APK获取签名读取失败，直接到路径下选择则正常
![1 00_00_00-00_00_30](https://github.com/xihan123/SignHook/assets/34203474/20232aa6-7a8d-46d1-9c9e-8b4a1f0688a9)
日志如下：
[LSPosed_2024-02-17T19_56_24.765911.zip](https://github.com/xihan123/SignHook/files/14318644/LSPosed_2024-02-17T19_56_24.765911.zip)

**Comment by xihan123** [comment]
特性就是这样，要从内部存储选择路径，而不是从最近或者其他地方

**Comment by aoguai** [comment]
我看有个关闭的 issues 也是一样的情况，如果是特性，感觉应该在 README.md 什么明显的地方说明一下

**Comment by xihan123** [comment]
> 我看有个关闭的 issues 也是一样的情况，如果是特性，感觉应该在 README.md 什么明显的地方说明一下

因为正常来说应该都是从内部存储选择吧？不是所有apk都会出现在最近页面中，而且我开发这个只是为了方便另一个软件，没想那么多
