### ISSUE TITLE
显示不出来软件是咋回事？

### ISSUE THREAD

**Issue by Minami373520** [xihan123/SignHook#125]

**Comment by xihan123** [comment]
?

**Comment by Minami373520** [comment]
> ?

![1708901878697.png](https://github.com/xihan123/SignHook/assets/118356738/b749024a-68b4-41c4-bdb8-9ce88a85935d)

就是安装了软件，但打开签名助手空空如也

**Comment by xihan123** [comment]
下拉刷新也没有吗

**Comment by Minami373520** [comment]
> 下拉刷新也没有吗

对的，啥都没有，空空如也，应该弄个授权应用的权限

**Comment by xihan123** [comment]
> > 下拉刷新也没有吗
> 
> 对的，啥都没有，空空如也，应该弄个授权应用的权限

没图也没日志说个🔨

**Comment by Minami373520** [comment]
> > > 下拉刷新也没有吗
> > 
> > 对的，啥都没有，空空如也，应该弄个授权应用的权限
> 
> 录个屏

这是别人的截图，说没有显示，我也不明白啥情况，所以我跑来问你了![Screenshot_2024-02-26-21-23-13-147_cn.xihan.sign.jpg](https://github.com/xihan123/SignHook/assets/118356738/3543204c-9e59-4cd9-b5c5-3114f13f82f9)

我用倒是可以正常显示

**Comment by xihan123** [comment]
> > > > 下拉刷新也没有吗
> > > 
> > > 
> > > 对的，啥都没有，空空如也，应该弄个授权应用的权限
> > 
> > 
> > 录个屏
> 
> 这是别人的截图，说没有显示，我也不明白啥情况，所以我跑来问你了![Screenshot_2024-02-26-21-23-13-147_cn.xihan.sign.jpg](https://private-user-images.githubusercontent.com/118356738/307807209-3543204c-9e59-4cd9-b5c5-3114f13f82f9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5NTkzNTMsIm5iZiI6MTcwODk1OTA1MywicGF0aCI6Ii8xMTgzNTY3MzgvMzA3ODA3MjA5LTM1NDMyMDRjLTllNTktNGNkOS1iNWM1LTMxMTRmMTNmODJmOS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNlQxNDUwNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mOGI0ZWM1MDExMmE2NzYzMjRjMmY4MDUyOWU0YTNkMWEwMjYwOWIzZjIzOTNlOTQ4YjIyODZlNzY1ZjUzM2ZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DdqZ29aLQblGtf9NFFljcrC8EZzEawSKba1UjBz0jkU)
> 
> 我用倒是可以正常显示

没有有用的信息那我就不知道了
