### ISSUE TITLE
2.0版本，获取签名错误

### ISSUE THREAD

**Issue by Junull** [xihan123/SignHook#127]
我目前使用的是最新版，也是选择APK——文件管理——内部存储设备——文件夹——文件夹里面选择的官方APK，提示获取签名错误。

**Comment by xihan123** [comment]
哪个app，我试试

**Comment by Junull** [comment]
> 哪个app，我试试

我提取的是知乎，和高德地图官方的APK，但都是获取签名错误，我不知道是不是其他的问题。

**Comment by Bejukoro** [comment]
同样情况，从任何 apk 都无法获取签名
系统版本 Android 14，ROM 是类原生 Evolution X

**Comment by xihan123** [comment]
> > 哪个app，我试试
> 
> 我提取的是知乎，和高德地图官方的APK，但都是获取签名错误，我不知道是不是其他的问题。

我这测试没问题

**Comment by xihan123** [comment]
> 同样情况，从任何 apk 都无法获取签名 系统版本 Android 14，ROM 是类原生 Evolution X

Android 14我还未测试，暂时没有空

**Comment by Junull** [comment]
> > > 哪个app，我试试
> > 
> > 我提取的是知乎，和高德地图官方的APK，但都是获取签名错误，我不知道是不是其他的问题。
> 
> 我这测试没问题

我是miui14 安卓12，已经root的设备但是提取任何apk都是错误，提不出来

**Comment by Bejukoro** [comment]
退回到 1.x 版本试了一下，1.x 版本中授予访问全部文件权限后可以顺利读取 apk 的签名
2.0 则无法读取签名，也没有申请访问文件权限

**Comment by xihan123** [comment]
还有一个更简单的方法，就是直接先安装原版的应用，然后在模块内刷新一下，复制获取到的原始签名即可

**Comment by Junull** [comment]
> 原始

这个我试过，就是麻烦。然后我退到上一版本发现可以提取到签名了，但是却无法伪装成功，而最新版却是无法提取，但是使用你讲的这个方法提取后却可以伪装成功。

**Comment by xihan123** [comment]
> > 原始
> 
> 这个我试过，就是麻烦。然后我退到上一版本发现可以提取到签名了，但是却无法伪装成功，而最新版却是无法提取，但是使用你讲的这个方法提取后却可以伪装成功。

上个版本因为存储权限问题作用域应用都无法读取到配置，所以伪装不了

**Comment by aoguai** [comment]
一样，任何APK无法获取签名

https://github.com/xihan123/SignHook/assets/34203474/20659c48-b8d1-4a01-adf3-506f04e5c1f3

[LSPosed_2024-02-29T21_15_32.148654.zip](https://github.com/xihan123/SignHook/files/14448494/LSPosed_2024-02-29T21_15_32.148654.zip)
