### ISSUE TITLE
lspatch的模块中无法查看到签名助手模块

### ISSUE THREAD

**Issue by yongxiangzheng** [xihan123/SignHook#135]
你好，试过签名助手安装了1.1.13版本跟2.0版本，在lspatch模块中查看不到，这个是什么原因呢？

**Comment by xihan123** [comment]
图呢

**Comment by yongxiangzheng** [comment]
https://github.com/xihan123/SignHook/assets/8653159/d487258f-5afe-425d-86f9-f9171fba44e3

您看下，手机型号vivo iqoo neo6se

**Comment by yongxiangzheng** [comment]
升级到2.0.1版本已经可以用了
