### ISSUE TITLE
将修补过的微信签名改为官方签名，其他官方app也还无法调用微信

### ISSUE THREAD

**Issue by yongxiangzheng** [xihan123/SignHook#137]
1.使用LSPatch修复微信，作用签名助手和闰二月模块
![0ef4b1be81d0593595ac5183a9a911d](https://github.com/xihan123/SignHook/assets/8653159/9e2dd3e1-20e9-4341-b376-6b3dda802c66)

2.使用签名助手伪装签名微信为官方签名
![2dac110b03f986671e348cff895dbd1](https://github.com/xihan123/SignHook/assets/8653159/d8d49036-be55-44d5-935a-12be3480f1c5)
![5b93448b291c7423d340a2bc2766c99](https://github.com/xihan123/SignHook/assets/8653159/b367e457-0b2a-4de9-9717-66457c191337)

3.重启微信和拼多多，使用拼多多登陆调用微信，提示未安装微信
![bc2d98c43dc56f6ecb17e5cc3fc7ce2](https://github.com/xihan123/SignHook/assets/8653159/b5d8368e-2c4c-4a97-ad0a-56979957819c)

请问这是什么原因，如何解决？
微信版本8.0.48，使用官方签名如下：308202eb30820254a00302010202044d36f7a4300d06092a864886f70d01010505003081b9310b300906035504061302383631123010060355040813094775616e67646f6e673111300f060355040713085368656e7a68656e31353033060355040a132c54656e63656e7420546563686e6f6c6f6779285368656e7a68656e2920436f6d70616e79204c696d69746564313a3038060355040b133154656e63656e74204775616e677a686f7520526573656172636820616e6420446576656c6f706d656e742043656e7465723110300e0603550403130754656e63656e74301e170d3131303131393134333933325a170d3431303131313134333933325a3081b9310b300906035504061302383631123010060355040813094775616e67646f6e673111300f060355040713085368656e7a68656e31353033060355040a132c54656e63656e7420546563686e6f6c6f6779285368656e7a68656e2920436f6d70616e79204c696d69746564313a3038060355040b133154656e63656e74204775616e677a686f7520526573656172636820616e6420446576656c6f706d656e742043656e7465723110300e0603550403130754656e63656e7430819f300d06092a864886f70d010101050003818d0030818902818100c05f34b231b083fb1323670bfbe7bdab40c0c0a6efc87ef2072a1ff0d60cc67c8edb0d0847f210bea6cbfaa241be70c86daf56be08b723c859e52428a064555d80db448cdcacc1aea2501eba06f8bad12a4fa49d85cacd7abeb68945a5cb5e061629b52e3254c373550ee4e40cb7c8ae6f7a8151ccd8df582d446f39ae0c5e930203010001300d06092a864886f70d0101050500038181009c8d9d7f2f908c42081b4c764c377109a8b2c70582422125ce545842d5f520aea69550b6bd8bfd94e987b75a3077eb04ad341f481aac266e89d3864456e69fba13df018acdc168b9a19dfd7ad9d9cc6f6ace57c746515f71234df3a053e33ba93ece5cd0fc15f3e389a3f365588a9fcb439e069d3629cd7732a13fff7b891499

**Comment by xihan123** [comment]
你试着给pdd也加上模块的作用域。其实你还没有搞懂调用者和被调用者的逻辑关系

**Comment by yongxiangzheng** [comment]
确实不是很理解，我的理解是，伪装微信签名为官方签名，其他app调用微信，就能正常调用了。

我按着你的建议，修补pdd，LSPach报错了，然后试着修补jd（本地模式），就能正常调用微信了。但是没有给jd加上任何作用域。之后把微信的作用域模块去掉签名助手，jd也能正常调用微信。说明能调用跟签名助手没关系，而是jd给修补的关系。

**Comment by xihan123** [comment]
> 确实不是很理解，我的理解是，伪装微信签名为官方签名，其他app调用微信，就能正常调用了。
> 
> 我按着你的建议，修补pdd，LSPach报错了，然后试着修补jd（本地模式），就能正常调用微信了。但是没有给jd加上任何作用域。之后把微信的作用域模块去掉签名助手，jd也能正常调用微信。说明能调用跟签名助手没关系，而是jd给修补的关系。

所以很明显，和签名助手没太大关系
是因为调用sdk校验了调用者的签名，如果校验了vx的签名理论上是可以通过的，具体我就没有测试了
毕竟我开发这个模块的主要原因还是为了解决qd调用第三方登录和分享的问题
只不过顺手就写了一套通用的逻辑出来

**Comment by pgy866** [comment]
我也遇到啦，LP修复的微信，无法被其他程序调用，由什么方法可以实现吗？

**Comment by naliyu** [comment]
我按照你的方法（本地模式）修补腾讯家的游戏，卸载老的，安装修复后的，游戏进去就闪退

**Comment by xihan123** [comment]
> 我按照你的方法（本地模式）修补腾讯家的游戏，卸载老的，安装修复后的，游戏进去就闪退

看日志具体是什么原因，光说明一个闪退解决不了任何问题

**Comment by xihan123** [comment]
> 这里讲不清，加我qq聊吧，3300716146

那就不必了

**Comment by xihan123** [comment]
> ![lspatch](https://private-user-images.githubusercontent.com/93574826/385696464-b24e3ef6-cffc-4144-851f-75dd90fae317.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0OTQ0OTEsIm5iZiI6MTczMTQ5NDE5MSwicGF0aCI6Ii85MzU3NDgyNi8zODU2OTY0NjQtYjI0ZTNlZjYtY2ZmYy00MTQ0LTg1MWYtNzVkZDkwZmFlMzE3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDEwMzYzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhNjNiZjA1ODNkNTQzNDVhYWQxNTUzYjQ2NjVlODRiZWI1MDBmZmMxNDFiNzY2ZThkMmE5OGI3NzM0ZjhkMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CMMos3dZD9DazIU93XbY_XKjzy6QEvCExytEPJ9jcqI) ![签名助手](https://private-user-images.githubusercontent.com/93574826/385696483-2930b803-a1ed-4898-83c1-c4b3a2279e11.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0OTQ0OTEsIm5iZiI6MTczMTQ5NDE5MSwicGF0aCI6Ii85MzU3NDgyNi8zODU2OTY0ODMtMjkzMGI4MDMtYTFlZC00ODk4LTgzYzEtYzRiM2EyMjc5ZTExLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDEwMzYzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlZTE0ZjlhN2NhZTg1NDQ3NjA0Mzg4MGQxNThhOGE0YWZjNTAyOTVlOTQxZDQ0NDQxNmMwODRiM2JlZWIzY2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.5sAVufRf2iUvhcRPedq5mRcn8B7lTxslkTFrsrUvbxg) 手机没root，微信的签名助手伪造了，但是微信是集成模式（嵌入了微X模块），所以没有修补进微信。 （本地模式）修补了这几个游戏， 掌上飞车多次打开没几秒闪退并显示 unable to connect to manager，成功识别到微信并登陆， 飞车（王者也是一样）多次打开没几秒闪退并显示 unable to connect to manager，后续直接闪退没有unable to connect to manager提示

你这个都是lspatch的问题了吧，没有日志没法知道问题
