### ISSUE TITLE
获取签名错误

### ISSUE THREAD

**Issue by yaoweigh** [xihan123/SignHook#141]
从正版安装包也获取不了签名

**Comment by xihan123** [comment]
图也没一个，你确定看明白使用说明了？

**Comment by yaoweigh** [comment]
> 图也没一个，你确定看明白使用说明了？

![Screenshot_2024-04-19-17-17-17-74_99c04817c0de5652397fc8b56c3b3817](https://github.com/xihan123/SignHook/assets/80156366/49bbf4a2-3ac8-4e8b-8202-c6ad114e5453)

**Comment by xihan123** [comment]
> > 图也没一个，你确定看明白使用说明了？
> 
> ![Screenshot_2024-04-19-17-17-17-74_99c04817c0de5652397fc8b56c3b3817](https://private-user-images.githubusercontent.com/80156366/323906632-49bbf4a2-3ac8-4e8b-8202-c6ad114e5453.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1MjI1NDIsIm5iZiI6MTcxMzUyMjI0MiwicGF0aCI6Ii84MDE1NjM2Ni8zMjM5MDY2MzItNDliYmY0YTItM2FjOC00ZThiLTgyMDItYzZhZDExNGU1NDUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDEwMjQwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2YjA4NzBmMjJhMmRiMjg3YmM1YjI4MTA5OTdlZDY3YTVkMDA0OTcyNzVkZGEwNThlN2ZiZDE1MmFhMDQyMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.N1ugQnFkJHY4ckl1k1vnDWDgpO6RJrRxPV2_IaHv-u0)

真就只给一个图吗，这个图并不能看出来什么，能不能仔细看一下readme 然后还不行就录个屏

**Comment by yaoweigh** [comment]
上次录了文件太大了传不了，剪掉没用的部分再传一次

https://github.com/xihan123/SignHook/assets/80156366/b3a94592-d5f8-485b-87c4-a75f9481546e

**Comment by xihan123** [comment]
> 上次录了文件太大了传不了，剪掉没用的部分再传一次
> 
>  VID_20240421145507.mp4

请把目标apk发我测试一下

**Comment by yaoweigh** [comment]
这是share微博的https://wwyt.lanzouw.com/tp/iQjn814bardc提取码9rd0 我试了其他官方正版app获取签名也是闪退比如网易云，我系统是realme5.0，但是用对话框取消可以获取签名信息

**Comment by xihan123** [comment]
> 这是share微博的[https://wwyt.lanzouw.com/tp/iQjn814bardc提取码9rd0](https://wwyt.lanzouw.com/tp/iQjn814bardc%E6%8F%90%E5%8F%96%E7%A0%819rd0) 我试了其他官方正版app获取签名也是闪退比如网易云，我系统是realme5.0，但是用对话框取消可以获取签名信息

我这测试读取正常，你会看日志吗，看看能不能看到相关报错日志
你发的这个应用签名是:

**Comment by MALTF** [comment]
@yaoweigh 参考这个试下[fix: Obtain original signature](https://github.com/xihan123/SignHook/pull/145)

**Comment by xihan123** [comment]
> @yaoweigh 参考这个试下[fix: Obtain original signature](https://github.com/xihan123/SignHook/pull/145)

主要是我没法复现，我类原生Android 13确实没有遇到这个问题

**Comment by MALTF** [comment]
> 主要是我没法复现，我类原生Android 13确实没有遇到这个问题

v2.0.1 版本 app/src/main/kotlin/cn/xihan/sign/ui/MainActivity.kt [源代码](https://github.com/xihan123/SignHook/blob/ef6bf52591c041c721f9b830d8488e7d33b3ff71/app/src/main/kotlin/cn/xihan/sign/ui/MainActivity.kt#L92)
Environment.getExternalStorageDirectory().path **->** /storage/emulated/0 
Android 6.0 以上这个需要申请权限才能读取到文件 否则报异常
Unable to open '/storage/emulated/0/NoCheck.apk': Permission denied
Failed to open APK '/storage/emulated/0/NoCheck.apk' I/O error
即使在AndroidManifest.xml添加
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
授权存储访问权限之后 在HUAWEI LIO-AN00m Android 10, API 29上测试后发现
app/src/main/kotlin/cn/xihan/sign/utli/Utils.kt [源代码](https://github.com/xihan123/SignHook/blob/master/app/src/main/kotlin/cn/xihan/sign/utli/Utils.kt#L104)
`val signatures = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
      packageInfo?.signingInfo?.apkContentsSigners
} else {
      packageInfo?.signatures
}`
packageInfo?.signingInfo 一直都是 null

[fix: obtain original signature #145](https://github.com/xihan123/SignHook/pull/145)
HUAWEI LIO-AN00m Android 10, API 29为例
文件放置到[文件管理->我的手机->Android->data->cn.cn.xihan.sign->cache]目录下
![screenshotFilePath](https://github.com/xihan123/SignHook/assets/15863058/25063d8e-900c-46a6-a833-6743b0ff33d0)

baseContext.externalCacheDir?.path **->** /storage/mutated/0/Android/data/cn.xihan.sign/cache
这个不需要存储访问权限就可以直接读取原始签名信息

**Comment by yaoweigh** [comment]
> > 这是share微博的[https://wwyt.lanzouw.com/tp/iQjn814bardc提取码9rd0](https://wwyt.lanzouw.com/tp/iQjn814bardc%E6%8F%90%E5%8F%96%E7%A0%819rd0) 我试了其他官方正版app获取签名也是闪退比如网易云，我系统是realme5.0，但是用对话框取消可以获取签名信息
> 
> 我这测试读取正常，你会看日志吗，看看能不能看到相关报错日志 你发的这个应用签名是: `308204a830820390a003020102020900936eacbe07f201df300d06092a864886f70d0101050500308194310b3009060355040613025553311330110603550408130a43616c69666f726e6961311630140603550407130d4d6f756e7461696e20566965773110300e060355040a1307416e64726f69643110300e060355040b1307416e64726f69643110300e06035504031307416e64726f69643122302006092a864886f70d0109011613616e64726f696440616e64726f69642e636f6d301e170d3038303232393031333334365a170d3335303731373031333334365a308194310b3009060355040613025553311330110603550408130a43616c69666f726e6961311630140603550407130d4d6f756e7461696e20566965773110300e060355040a1307416e64726f69643110300e060355040b1307416e64726f69643110300e06035504031307416e64726f69643122302006092a864886f70d0109011613616e64726f696440616e64726f69642e636f6d30820120300d06092a864886f70d01010105000382010d00308201080282010100d6931904dec60b24b1edc762e0d9d8253e3ecd6ceb1de2ff068ca8e8bca8cd6bd3786ea70aa76ce60ebb0f993559ffd93e77a943e7e83d4b64b8e4fea2d3e656f1e267a81bbfb230b578c20443be4c7218b846f5211586f038a14e89c2be387f8ebecf8fcac3da1ee330c9ea93d0a7c3dc4af350220d50080732e0809717ee6a053359e6a694ec2cb3f284a0a466c87a94d83b31093a67372e2f6412c06e6d42f15818dffe0381cc0cd444da6cddc3b82458194801b32564134fbfde98c9287748dbf5676a540d8154c8bbca07b9e247553311c46b9af76fdeeccc8e69e7c8a2d08e782620943f99727d3c04fe72991d99df9bae38a0b2177fa31d5b6afee91f020103a381fc3081f9301d0603551d0e04160414485900563d272c46ae118605a47419ac09ca8c113081c90603551d230481c13081be8014485900563d272c46ae118605a47419ac09ca8c11a1819aa48197308194310b3009060355040613025553311330110603550408130a43616c69666f726e6961311630140603550407130d4d6f756e7461696e20566965773110300e060355040a1307416e64726f69643110300e060355040b1307416e64726f69643110300e06035504031307416e64726f69643122302006092a864886f70d0109011613616e64726f696440616e64726f69642e636f6d820900936eacbe07f201df300c0603551d13040530030101ff300d06092a864886f70d010105050003820101007aaf968ceb50c441055118d0daabaf015b8a765a27a715a2c2b44f221415ffdace03095abfa42df70708726c2069e5c36eddae0400be29452c084bc27eb6a17eac9dbe182c204eb15311f455d824b656dbe4dc2240912d7586fe88951d01a8feb5ae5a4260535df83431052422468c36e22c2a5ef994d61dd7306ae4c9f6951ba3c12f1d1914ddc61f1a62da2df827f603fea5603b2c540dbd7c019c36bab29a4271c117df523cdbc5f3817a49e0efa60cbd7f74177e7a4f193d43f4220772666e4c4d83e1bd5a86087cf34f2dec21e245ca6c2bb016e683638050d2c430eea7c26a1c49d3760a58ab7f1a82cc938b4831384324bd0401fa12163a50570e684d`

lsposd日志里能看到么

**Comment by xihan123** [comment]
> > > 这是share微博的[https://wwyt.lanzouw.com/tp/iQjn814bardc提取码9rd0](https://wwyt.lanzouw.com/tp/iQjn814bardc%E6%8F%90%E5%8F%96%E7%A0%819rd0) 我试了其他官方正版app获取签名也是闪退比如网易云，我系统是realme5.0，但是用对话框取消可以获取签名信息
> > 
> > 
> > 我这测试读取正常，你会看日志吗，看看能不能看到相关报错日志 你发的这个应用签名是: `308204a830820390a003020102020900936eacbe07f201df300d06092a864886f70d0101050500308194310b3009060355040613025553311330110603550408130a43616c69666f726e6961311630140603550407130d4d6f756e7461696e20566965773110300e060355040a1307416e64726f69643110300e060355040b1307416e64726f69643110300e06035504031307416e64726f69643122302006092a864886f70d0109011613616e64726f696440616e64726f69642e636f6d301e170d3038303232393031333334365a170d3335303731373031333334365a308194310b3009060355040613025553311330110603550408130a43616c69666f726e6961311630140603550407130d4d6f756e7461696e20566965773110300e060355040a1307416e64726f69643110300e060355040b1307416e64726f69643110300e06035504031307416e64726f69643122302006092a864886f70d0109011613616e64726f696440616e64726f69642e636f6d30820120300d06092a864886f70d01010105000382010d00308201080282010100d6931904dec60b24b1edc762e0d9d8253e3ecd6ceb1de2ff068ca8e8bca8cd6bd3786ea70aa76ce60ebb0f993559ffd93e77a943e7e83d4b64b8e4fea2d3e656f1e267a81bbfb230b578c20443be4c7218b846f5211586f038a14e89c2be387f8ebecf8fcac3da1ee330c9ea93d0a7c3dc4af350220d50080732e0809717ee6a053359e6a694ec2cb3f284a0a466c87a94d83b31093a67372e2f6412c06e6d42f15818dffe0381cc0cd444da6cddc3b82458194801b32564134fbfde98c9287748dbf5676a540d8154c8bbca07b9e247553311c46b9af76fdeeccc8e69e7c8a2d08e782620943f99727d3c04fe72991d99df9bae38a0b2177fa31d5b6afee91f020103a381fc3081f9301d0603551d0e04160414485900563d272c46ae118605a47419ac09ca8c113081c90603551d230481c13081be8014485900563d272c46ae118605a47419ac09ca8c11a1819aa48197308194310b3009060355040613025553311330110603550408130a43616c69666f726e6961311630140603550407130d4d6f756e7461696e20566965773110300e060355040a1307416e64726f69643110300e060355040b1307416e64726f69643110300e06035504031307416e64726f69643122302006092a864886f70d0109011613616e64726f696440616e64726f69642e636f6d820900936eacbe07f201df300c0603551d13040530030101ff300d06092a864886f70d010105050003820101007aaf968ceb50c441055118d0daabaf015b8a765a27a715a2c2b44f221415ffdace03095abfa42df70708726c2069e5c36eddae0400be29452c084bc27eb6a17eac9dbe182c204eb15311f455d824b656dbe4dc2240912d7586fe88951d01a8feb5ae5a4260535df83431052422468c36e22c2a5ef994d61dd7306ae4c9f6951ba3c12f1d1914ddc61f1a62da2df827f603fea5603b2c540dbd7c019c36bab29a4271c117df523cdbc5f3817a49e0efa60cbd7f74177e7a4f193d43f4220772666e4c4d83e1bd5a86087cf34f2dec21e245ca6c2bb016e683638050d2c430eea7c26a1c49d3760a58ab7f1a82cc938b4831384324bd0401fa12163a50570e684d`
> 
> lsposd日志里能看到么

试一下2.0.2版本

**Comment by MALTF** [comment]
@yaoweigh  你安装这个试试 [SignHook-release_2.0.3-T_191.apk](https://github.com/MALTF/SignHook/releases/download/v2.0.3-T/SignHook-release_2.0.3-T_191.apk)

**Comment by yaoweigh** [comment]
> > > > 这是share微博的[https://wwyt.lanzouw.com/tp/iQjn814bardc提取码9rd0](https://wwyt.lanzouw.com/tp/iQjn814bardc%E6%8F%90%E5%8F%96%E7%A0%819rd0) 我试了其他官方正版app获取签名也是闪退比如网易云，我系统是realme5.0，但是用对话框取消可以获取签名信息
> > > 
> > > 
> > > 我这测试读取正常，你会看日志吗，看看能不能看到相关报错日志 你发的这个应用签名是: `308204a830820390a003020102020900936eacbe07f201df300d06092a864886f70d0101050500308194310b3009060355040613025553311330110603550408130a43616c69666f726e6961311630140603550407130d4d6f756e7461696e20566965773110300e060355040a1307416e64726f69643110300e060355040b1307416e64726f69643110300e06035504031307416e64726f69643122302006092a864886f70d0109011613616e64726f696440616e64726f69642e636f6d301e170d3038303232393031333334365a170d3335303731373031333334365a308194310b3009060355040613025553311330110603550408130a43616c69666f726e6961311630140603550407130d4d6f756e7461696e20566965773110300e060355040a1307416e64726f69643110300e060355040b1307416e64726f69643110300e06035504031307416e64726f69643122302006092a864886f70d0109011613616e64726f696440616e64726f69642e636f6d30820120300d06092a864886f70d01010105000382010d00308201080282010100d6931904dec60b24b1edc762e0d9d8253e3ecd6ceb1de2ff068ca8e8bca8cd6bd3786ea70aa76ce60ebb0f993559ffd93e77a943e7e83d4b64b8e4fea2d3e656f1e267a81bbfb230b578c20443be4c7218b846f5211586f038a14e89c2be387f8ebecf8fcac3da1ee330c9ea93d0a7c3dc4af350220d50080732e0809717ee6a053359e6a694ec2cb3f284a0a466c87a94d83b31093a67372e2f6412c06e6d42f15818dffe0381cc0cd444da6cddc3b82458194801b32564134fbfde98c9287748dbf5676a540d8154c8bbca07b9e247553311c46b9af76fdeeccc8e69e7c8a2d08e782620943f99727d3c04fe72991d99df9bae38a0b2177fa31d5b6afee91f020103a381fc3081f9301d0603551d0e04160414485900563d272c46ae118605a47419ac09ca8c113081c90603551d230481c13081be8014485900563d272c46ae118605a47419ac09ca8c11a1819aa48197308194310b3009060355040613025553311330110603550408130a43616c69666f726e6961311630140603550407130d4d6f756e7461696e20566965773110300e060355040a1307416e64726f69643110300e060355040b1307416e64726f69643110300e06035504031307416e64726f69643122302006092a864886f70d0109011613616e64726f696440616e64726f69642e636f6d820900936eacbe07f201df300c0603551d13040530030101ff300d06092a864886f70d010105050003820101007aaf968ceb50c441055118d0daabaf015b8a765a27a715a2c2b44f221415ffdace03095abfa42df70708726c2069e5c36eddae0400be29452c084bc27eb6a17eac9dbe182c204eb15311f455d824b656dbe4dc2240912d7586fe88951d01a8feb5ae5a4260535df83431052422468c36e22c2a5ef994d61dd7306ae4c9f6951ba3c12f1d1914ddc61f1a62da2df827f603fea5603b2c540dbd7c019c36bab29a4271c117df523cdbc5f3817a49e0efa60cbd7f74177e7a4f193d43f4220772666e4c4d83e1bd5a86087cf34f2dec21e245ca6c2bb016e683638050d2c430eea7c26a1c49d3760a58ab7f1a82cc938b4831384324bd0401fa12163a50570e684d`
> > 
> > 
> > lsposd日志里能看到么
> 
> 试一下2.0.2版本

可以获取了

**Comment by yaoweigh** [comment]
> @yaoweigh 你安装这个试试 [SignHook-release_2.0.3-T_191.apk](https://github.com/MALTF/SignHook/releases/download/v2.0.3-T/SignHook-release_2.0.3-T_191.apk)

嗯嗯，可以的

**Comment by pgy866** [comment]
SignHook-release_2.0.3_194.apk   鸿蒙2.0 也有这个而问题，给啦存储权限也这样

**Comment by MALTF** [comment]
> SignHook-release_2.0.3_194.apk 鸿蒙2.0 也有这个而问题，给啦存储权限也这样

这个是了嘛，可以不？[SignHook-release_2.0.3-T_191.apk](https://github.com/MALTF/SignHook/releases/download/v2.0.3-T/SignHook-release_2.0.3-T_191.apk)¿
