### ISSUE TITLE
[Bug&咨询] 我的华为手机卡在Apk选择这一关，因为我用什么方式选择apk都只会返回 获取签名错误

### ISSUE THREAD

**Issue by 8MiYile** [xihan123/SignHook#157]
在选择Apk这一关，不管是选择最近还是选择下载内容，亦或者是自己的手机型号，再或者是底下的文件管理和MT管理器内选择文件，都会提示获取签名错误
如果作者方便的话，我希望这个应用能出个jar版本的，我想直接从GitHub Actions那边读取

**Comment by xihan123** [comment]
其实想获取源签名也可以先安装原版，然后刷新一下把签名复制下来就可以了
另外jar版估计是没法弄
