### ISSUE TITLE
微信签名校验通过失败

### ISSUE THREAD

**Issue by pasical** [xihan123/SignHook#166]
![Screenshot_2024-08-02-00-42-25-040_tv.danmaku.bili.jpg](https://github.com/user-attachments/assets/2edbcba6-8f29-4616-823f-563e9af75e45)

![Screenshot_2024-08-02-00-45-12-280_com.tencent.mobileqq.jpg](https://github.com/user-attachments/assets/fedb9299-6648-4a74-bc23-c09827b384e4)

如图，微信在8.0.50版本中没有能够成功hook，QQ的9.0.56版本成功通过。模块版本2.0.3，微信、QQ都在作用域，并且强行停止后复现。

**Comment by pasical** [comment]
原因可能是哔哩哔哩自己改签名了🤔（还能有这种事？不会吧），重新提取一遍就好了

**Comment by xihan123** [comment]
？？？？？你在说什么

**Comment by pasical** [comment]
> ？？？？？你在说什么

这件事从头到尾都挺莫名其妙的，就是分享到QQ可以，但是微信不行。我应该全程没有什么操作错误（可能我的标题有点误导？），之前也一直都可以正常分享到微信，昨天突然就不行了。

我把所有东西都检查过了一遍，包括：关模块，强行停止Q、V，分享，当然两者都不能成功，开模块，强行停止，分享，Q可以但V不行。

最后的解决方式是，下载官方b站包，提取签名，重新伪装，然后就可以了。证明应该是我的设备的偶发情况。

总之，就是一个突然不行到突然又行了的过程。基本不可能是模块的bug。

**Comment by xihan123** [comment]
好好好，这才是一个正常人应该做的，给你点赞
那些一上来就问为什么不能用，怎么失效了的我真的没话说
