### ISSUE TITLE
某民K歌不行

### ISSUE THREAD

**Issue by lezhengsiyuan** [xihan123/SignHook#169]
都按照你的文档步骤操作，也尝试了都勾选或者只勾选某民K歌，结果都不行，原版签名是：
308203653082024da00302010202042ce3a36e300d06092a864886f70d01010b05003063310e300c060355040613056368696e61310b300906035504081302737a310b300906035504071302737a3110300e060355040a130774656e63656e743110300e060355040b130774656e63656e74311330110603550403130a7368696e656875616e67301e170d3134303830363037343630305a170d3203830333037343630305a3063310e300c060355040613056368696e61310b300906035504081302737a310b300906035504071302737a3110300e060355040a13077e63656e743110300e060355040b130774656e63656e74311330110603550403130a7368696e656875616e6730820122300d06092a864886f70d01010105000382010f003082010a028201010090d1f0d7b066a0047c631a34d28814908ff19d35e61f00739fdb09c1d220ce5705c281581df556a9f8faf503fa347f822b5acdf6409f5918d39012e22ba63a7fc81e772dab1a6afec82c7959300c0ab0785037b41a84b36111e677ef9f6206b2fedeaa00a254be4b3c0920454c1b9db2ababe0c629378cd793fe0a9af0bb945adcfbf7732bb7e127644a7bdbbcf2184f1457dd1286a3b549aab7ef935ab6f48c70a8c77fc6975552c55edc6945a160de00d3b9d81de454203e43492702a6b2610a2c511d4d70dfb70f956c1a9662da16fdb5e04a94a41325400738c60f5e4975dd59f386b2244b8ecdfd08db2ee8fd9c288d07538cf20076448b1bb6902256ad0203010001a321301f301d0603551d0e04160414ec9d771782246e42548a8674ded6f7fbbdce3afe300d06092a864886f70d01010b05000382010100857f26b9861f12ea3c3f6d7060cd1c1d347fda6688f6533ff3343a8d83538e2ed36f03f14d4ecaa073e2aa61e0852a4ad0f38d9aebd289aa037a84d2ab029412a91825bba92437bb02cf0ff90a7615fe8197ad1a07a84f567053f3565819845323413d2bb77eceae12459592949641b11ecbf8f7db4a4deea52882f8d6da8c88d7cdb374709f6cf54cc06bd237279fe99eb7e579d279189162033ad841b7cb929a906363e1f9cda6025370296d3065cdddafdf730913d8cd7df7a9df694b35c1c1247be18f21e56d4c7976fcb1c8ad97cfc85b11a9b8a0a7f882d5501ce6cb83854ac44fd0ed0ab6bafb182b1d80f6e56a20cc32d424776e41f2ddab81db0a84
![80719e30af6c0df3b2005bdb7d5601e](https://github.com/user-attachments/assets/1305ede7-00da-4c96-bf27-c02254c1caf6)
![0b388ddb0ccc4182461fcae77d3ab16](https://github.com/user-attachments/assets/453679aa-742f-495a-a632-be3d45870698)
![f4c49e0313f64ef832edcdedce12b1d](https://github.com/user-attachments/assets/f8fb2a9d-8cbb-4cd7-8cb4-c2e134178e9c)

**Comment by xihan123** [comment]
一般来说lsp作用域不需要勾选目标应用，一般被调用者才需要勾选，还有要注意签名助手的版本，过低的不支持Q9以上

**Comment by lezhengsiyuan** [comment]
> 一般来说lsp作用域不需要勾选目标应用，一般被调用者才需要勾选，还有要注意签名助手的版本，过低的不支持Q9以上
> 
> 这个应用我早就试过完全可以用，你步骤或者方法错了
我也尝试了只勾选全民K歌，另外签名助手版本2.0.3,麻烦你帮我看一下

**Comment by xihan123** [comment]
所以你没有捋清楚逻辑，调用者和被调用者的关系，k歌才是调用者，qq是被调用的，你需要做的是先强行停止qq然后修改模块里目标的签名，重新打开qq这样

**Comment by lezhengsiyuan** [comment]
好的谢谢

**Comment by lezhengsiyuan** [comment]
那这个调用的原理是什么呀：
从过程来看是K歌先调用qq的活动，然后QQ检测了K歌的签名，最后检测到签名不对再报错，是吗？

**Comment by xihan123** [comment]
> 那这个调用的原理是什么呀： 从过程来看是K歌先调用qq的活动，然后QQ检测了K歌的签名，最后检测到签名不对再报错，是吗？

QQ的调用原理要不你去问QQ？

**Comment by lezhengsiyuan** [comment]
那你的项目原理不是修改了qq返回的签名值吗

**Comment by xihan123** [comment]
项目的原理是修改了系统返回的签名值

**Comment by lezhengsiyuan** [comment]
那这样的话qq也是调用系统api的？

**Comment by xihan123** [comment]
话说你是有框架为什么还要修改K歌本体？

**Comment by lezhengsiyuan** [comment]
就是想学习一下原理，hook的话也学了

**Comment by pgy866** [comment]
我是京东，多多，都提示未安装，转转提示请重正规渠道安装微信，不知道怎么弄？

**Comment by xihan123** [comment]
> 我是京东，多多，都提示未安装，转转提示请重正规渠道安装微信，不知道怎么弄？ 但是我全民k歌，调用qq,微信登陆都正常，分享就不行，提示未安装 网易云也没法分享

分享的话那就不知道了，至少起点我测试过是可以分享的
