### ISSUE TITLE
列表页不显示签名且无法修改签名

### ISSUE THREAD

**Issue by NormalAlkene** [xihan123/SignHook#175]
安装之后（已在 LSPosed 框架中启用并勾选作用域，已重启）下拉刷新，列表页只显示应用名称与包名，不显示签名，也无法修改签名（见下图）。

是否给予 Root 权限均不可行，不知道是不是哪里配置有问题。

![1732119087580](https://github.com/user-attachments/assets/dd3e9ab5-a362-4177-bc8d-497260edcc4a)

签名助手版本：v2.0.3
手机型号：红米 Note 11T Pro
系统版本：MIUI Global 14.0.7 (Android 13)
Root 提供应用：KernelSU v11928
LSPosed 框架：1.9.3_mod，通过 Zygisk LSPosed

**Comment by xihan123** [comment]
点一下应用名称展开

**Comment by NormalAlkene** [comment]
还真是，点击“应用名称”四个字才可以，感谢大佬
