### ISSUE TITLE
为什么选择Apk后什么也没发生？

### ISSUE THREAD

**Issue by bimzcy** [xihan123/SignHook#25]
不是说这么做以后可以复制签名吗？结果选择了Apk文件后啥也没发生就又回到列表页了

**Comment by xihan123** [comment]
> 不是说这么做以后可以复制签名吗？结果选择了Apk文件后啥也没发生就又回到列表页了

你确定你选择了正确有效的apk?没有相关日志提供建议录个屏

**Comment by Timibabu** [comment]
我的也是这样，选择APP后直接跳转到列表页了

https://github.com/xihan123/SignHook/assets/140060715/b7d7dbcf-7b16-4c24-9b90-a0227eddbd3b

**Comment by xihan123** [comment]
经测试，大概率是目标应用的签名无效，检查一下签名是否有效吧
