### ISSUE TITLE
提一个对han大来说可能不是“有用”的建议😜

### ISSUE THREAD

**Issue by P3R5T7U9** [xihan123/SignHook#30]
想问下han大，不知有无可能在这个仓库的Actions中给一些runs提供编译成品(也即：Artifacts)此内容？？如：LibChecker这个仓库的Actions，每5个runs有2～3个runs就有相应的编译成品，如下截图我所圈部分：
![](https://z4a.net/images/2023/07/19/IMG_20230719_140648.jpg)

看han大在此仓库每隔一段时间才发布正式版，我也翻了此仓库的Actions中大多数runs，只有编译状态结果，没有对应的Artifacts，这样对一些只想食用“内测版”的“勇士”(就比如我)，等待每个正式版时间有些长，快成“急急国王”惹，而且也无法通过“内测版”获取每个更新特性😖
(小声：如果han大认为在Action中的每个run都提供相应的Artifacts，时间一长，会占用个人Action的大量免费空间，得不偿失的话，暂不考虑也行)

**Comment by xihan123** [comment]
也没啥更新，没有必要搞这个啊，后续开发计划也未定
