### ISSUE TITLE
提示签名读取失败

### ISSUE THREAD

**Issue by VnchowWang** [xihan123/SignHook#85]
![Screenshot_2023-10-04-23-59-10-232_cn xihan sign](https://github.com/xihan123/SignHook/assets/94701290/d2a42d4f-1ada-42dc-813c-b08e4db83b73)

**Comment by xihan123** [comment]
读取的Apk文件签名有问题

**Comment by VnchowWang** [comment]
> 读取的Apk文件签名有问题

所有的文件都是这样的提示，包括官方版，任何一个apk都不行

**Comment by xihan123** [comment]
> > 读取的Apk文件签名有问题
> 
> 所有的文件都是这样的提示，包括官方版，任何一个apk都不行

录屏

**Comment by VnchowWang** [comment]
> > > 读取的Apk文件签名有问题
> > 
> > 
> > 所有的文件都是这样的提示，包括官方版，任何一个apk都不行
> 
> 录屏

**Comment by VnchowWang** [comment]
这样

**Comment by 1045925330** [comment]
https://github.com/xihan123/SignHook/assets/30003970/0f298697-c5a2-4538-a99c-8d210b44b4e3

app自带的获取签名无法使用，怎么通过其他方法获得？

**Comment by xihan123** [comment]
我这读取是正常的，可能是你设备或者其他方面问题
另外哔哩的签名值为:
